#    ___  ___ _ __   __ _ _ __  ___  ___  
#   / _ \/ __| '_ \ / _` | '_ \/ __|/ _ \ 
#  |  __/\__ \ |_) | (_| | | | \__ \ (_) |
#   \___||___/ .__/ \__,_|_| |_|___/\___/ 
#            |_|                         

# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
toggle_key: OFF

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: "ap@"
    replace: "adityapudipeddi@gmail.com"
    
  - trigger: "ax@"
    replace: "adityaaxelblaze@gmail.com"

  - trigger: "app@"
    replace: "aditya.pudipeddi@postman.com"

  - trigger: "home@"
    replace: "45-50-9, GF3, Raj Enclave, Abidnagar, Akkayyapalem, Visakhapatnam, Andhra Pradesh - 530016"

  - trigger: "docker@"
    replace: "docker exec -it $(docker ps -q) bash"

  - trigger: "logs@"
    replace: "./node_modules/.bin/pm2 logs"
  
  - trigger: "models@"
    replace: "./node_modules/@postman/newman-remote-models/"

  - trigger: "yakuza@"
    replace: "In Japan, heart surgeon. Number one. Steady hand. One day, Yakuza boss need new heart. I do operation. But, mistake! Yakuza boss die! Yakuza very mad. I hide in fishing boat, come to America. No english, no food, no money. Darryl give me job. Now I have house, American car, and new woman. Darryl save life. My big secret: I kill yakuza boss on purpose. I good surgeon. The best!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"